uploads:
  build: ./uploads
  volumes:
   - "/uploads"
wpdb:
  build: ./mysql
  environment:
    MYSQL_PASS: "6gdP7R3adDYNehj"
wp:
  build: .
  command:
   - "/run.sh"
  ports:
   - "80:80"
  expose:
   - "80"
  volumes_from:
   - "uploads"
  links:
   - "wpdb:wpdb"
  environment:
    - DB_NAME=wp_test
    - DB_USER=admin
    - DB_PASS=6gdP7R3adDYNehj
